old_trademaster/homepage/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views

app_name = 'homepage'
urlpatterns = [
    url(r'^homepage$', views.HomePage2, name='home'),

    url(r'^$', views.Welcome, name='welcome'),

    url(r'^boot$', views.Boot, name='boot'),


    url(r'^register/$', views.register, name='register'), # ADD NEW PATTERN!

    url(r'^login/$', views.user_login, name='login'),

    url(r'^logout/$', views.user_logout, name='logout'),

    
    
]

old_trademaster/homepage/templates/homepage/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{% block tabtitle %}  tab title {% endblock%}</title>




	   <!-- <link rel="stylesheet" href="styles2.css"> -->
	   <!-- <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script> -->


	   	<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
		<script src="{% static 'charting/jquery-lazyload/jquery.lazyload.js' %}"></script>
		<script src="{% static 'charting/jquery-lazyload/jquery.lazyload.js' %}"></script>

		

		<script type="text/javascript">
		
		$(function() {
			// $("img.lazy").lazyload({failure_limit : 10,event : "mouseover",threshold : 200});
			// $("img.lazy").lazyload();
			$("img.lazy").lazyload({ event: "scrollstop", failure_limit : 1000});
		});

		$(function() {
    		$("img.lazy").lazyload({ event: "scrollstop",failure_limit : 1000,container: $("#container")});
  		});
		
		// $("#container").each(function() {
		//     var tthis = $(this);
		//     $(this).find('img.lazy').lazyload({event: "scrollstop",failure_limit : 10000,
		//         container: tthis
		//     });
		// });
		// $("#container").each(function() {
		//     var tthis = $(this);
		//     $(this).find('img').lazyload({
		//         container: tthis
		//     });
		// });
		</script>
		<script src="{% static 'research/jquery.scrollstop.js' %}" type="text/javascript"></script> 

		<!-- icons -->
		<!--link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png"-->
		<!--link rel="shortcut icon" href="favicon.ico"-->

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" type="text/css" href="{% static 'homepage/styles_eg.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'homepage/styles2.css' %}" />

		<style type="text/css">
		.TFtable{
			border : 0;
			border-spacing: 7px;
    		border-collapse: separate;
		}
		.TFtable th{
			align:center;
			text-align: center;
			font-family: "Times New Roman", Times, serif;
			font-size: 110%;
			padding:7px;
		}
		  .TFtable td{ 
		  	text-align: center;
			padding:7px; 
			border:#4e95f4 1px solid;,
			align:center;
		  }
		  /* provide some minimal visual accomodation for IE8 and below */

		  /*  Define the background color for all the ODD background rows  */
		  .TFtable tr:nth-child(odd){ 
			background: #e6f7ff;
		  }

		</style>
		
		{% block head %}

		{% endblock %} 

	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">  {% block title%}Default title{% endblock%}  </h1>
			</div>
		</div>


<div id='cssmenu'>

<ul>
   <li><a href="{% url 'homepage:welcome' %}"><span>Getting Started</span></a></li>
   <li><a href="{% url 'homepage:home' %}"><span>Home</span></a></li>
   <li><a href="{% url 'homepage:boot' %}"><span>boot</span></a></li>
   <li class='active has-sub' ><a href="{% url 'research:windowquerytool_advanced' %}"><span>Research</span></a>
   		<ul>
   			<li><a href="{% url 'research:windowquerytool_advanced' %}"><span>Custom Stock Query </span></a></li>
   			<li><a href="{% url 'research:createmodifyfeature' %}"><span>Create/Modify Custom Features </span></a></li>

   			<li><a href="{% url 'research:study' %}"><span>Study a Stock </span></a></li>
   			<li><a href="{% url 'research:researchstatus' %}"><span>Compute Status </span></a></li>
   			<li><a href="{% url 'research:ComputeLog' %}"><span>Compute Log </span></a></li>
   			<li class='last'><a href="{% url 'research:category' %}"><span>Categories </span></a></li>

   		</ul>
   	</li>

   
   <li class='active has-sub' ><a href="{% url 'research:learning' %}"><span>Machine Learning</span></a>
   		<ul>
   			<li class='last'><a href="{% url 'research:learning' %}"><span>Data Set 1 </span></a></li>
   		</ul>
   </li>


   <li class='active has-sub' ><a href="{% url 'stockdata:viewwatchlist' %}"><span>Watch List</span></a>
   		<ul>
   			<li><a href="{% url 'stockdata:viewwatchlist' %}"><span>View Watchlist </span></a></li>
   			<li><a href="{% url 'stockdata:watchlistmanager_create' %}"><span>Create Watchlist </span></a></li>
   			<li class='last'><a href="{% url 'stockdata:watchlistmanager_amend' %}"><span>Modify Watchlist </span></a></li>
   		</ul>
   </li>

   <li class='active has-sub' ><a href="{% url 'charting:viewcharts' %}"><span>View Charts</span></a></li>

   

   

   <li><a href="{% url 'homepage:register' %}"><span>Register</span></a></li>
   <li><a href="{% url 'homepage:login' %}"><span>Log in</span></a></li>
   {% if user.is_authenticated %}
   		{% ifequal user.username "nagavenkat" %}
   			<li><a href="{% url 'stockdata:controlpanel' %}"><span>Control Panel</span></a></li>
   			<li><a href="/admin"><span>Admin</span></a></li>
		{% endifequal %}
	{% endif %}

   <li class='last'><a href="{% url 'homepage:logout' %}"><span>Log out</span></a></li>
</ul>


</div>


		<div class="content">
			<div class="container">
				<div class="main">
					{% block pagemain %} 

					Page 1 

					{% endblock %}
					
					

				</div>
			</div>
		</div>

		<div class="footer">
			<div class="container">
				
			</div>
		</div>
		
	</body>
</html>

old_trademaster/homepage/templates/homepage/base2.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/favicon.ico">

    <title>{% block tabtitle %}  tab title {% endblock%}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'homepage/Bootstrap_files/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'homepage/Bootstrap_files/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static 'homepage/Bootstrap_files/navbar.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'homepage/Bootstrap_files/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Trade Coach</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

              <li class="active"><a href="{% url 'homepage:welcome' %}"><span>Getting Started</span></a></li>

              <li><a href="{% url 'homepage:home' %}"><span>Home</span></a></li>

              <li class="dropdown">
                <a href="{% url 'research:windowquerytool_advanced' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span>Research</span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                      <li><a href="{% url 'research:windowquerytool_advanced' %}"><span>Custom Stock Query </span></a></li>
                      <li><a href="{% url 'research:createmodifyfeature' %}"><span>Create/Modify Custom Features </span></a></li>
                      <li><a href="{% url 'research:study' %}"><span>Study a Stock </span></a></li>
                      <li><a href="{% url 'research:researchstatus' %}"><span>Compute Status </span></a></li>
                      <li><a href="{% url 'research:ComputeLog' %}"><span>Compute Log </span></a></li>
                      <li class='last'><a href="{% url 'research:category' %}"><span>Categories </span></a></li>
                </ul>
              </li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p>This example is a quick exercise to illustrate how the default, static navbar and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
        <p>
          <a class="btn btn-lg btn-primary" href="https://getbootstrap.com/components/#navbar" role="button">View navbar docs »</a>
        </p>
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'homepage/Bootstrap_files/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'homepage/Bootstrap_files/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'homepage/Bootstrap_files/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

old_trademaster/homepage/templates/homepage/homepage.html
{% extends "homepage/base.html" %} 
{% load staticfiles %}

{% block tabtitle %}  Query Tool {% endblock%}

{% block head %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script> -->
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="{% static 'research/jquery_chained/jquery.chained.js' %}" type="text/javascript" charset="utf-8"></script>


  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet"  href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  <link rel="stylesheet" href="{% static 'research/tablesorter/themes/blue/style.css' %}" type="text/css" media="print, projection, screen" />
  <script type="text/javascript" src="{% static 'research/tablesorter/jquery.tablesorter.js' %}"></script> 

<!-- <script type="text/javascript">
			$(function() {
			$("img.lazy").lazyload({failure_limit : 10});
		});
</script> -->

{% endblock %}

{% block title %}Home Page{% endblock %}

{% block pagetitle %} Home page {% endblock %}

{% block pagemain %} 

<script type="text/javascript">
{% for sq,sqdata in SavedQueriesView.items  %}	
	$(function() {
    		$("img.lazy").lazyload({ event: "scrollstop",failure_limit : 10000,container: $("#container{{forloop.counter0}}")});
  		});

{% endfor %}
</script>

<h1>DashBoard</h1>

<table>

{% for sq,sqdata in SavedQueriesView.items  %}
		<tr>
			<td>
				<h2 style="font-family: 'Ultra', sans-serif; font-weight: normal;margin: 1em 0 0.5em 0;">{{sq}}</h2>
				<div id="container{{forloop.counter0}}" style="border-radius: 25px; box-shadow: 10px 10px 5px #888888;background: #d6e0f5;padding: 20px;margin: 20px; height:600px;overflow-y: auto;white-space: nowrap;">
					
						<table>
							<tr><td>
								<table>
									<tr>
										{% for chrtname,chart in sqdata.SummaryCharts.items %}
											{% if 'Industry' not in chrtname %}
											<td style="border-left: 1px solid #cdd0d4;">
												<h6>{{chrtname}}</h6>
												{{chart}}
											</td>
											{% endif %}
										{% endfor %}
									</tr>
								</table>
							</td></tr>
							<tr><td>
								<table>
									<tr>
								{% for chrtname,chart in sqdata.SummaryCharts.items %}
									{% if 'Industry' in chrtname %}
									<td valign="top" style="border-left: 1px solid ">
										<h6>{{chrtname}}</h6>
										{{chart}}
									</td>
									{% endif %}
								{% endfor %}
									</tr>
								</table>
							</td></tr>
						</table>
						<table>
							
								{% for rows in sqdata.Table  %}
									<tr>
									{% for img in rows  %}
										<td valign="top">{{img}}</td>
									{%endfor%}
									</tr>

								{%endfor%}
						</table>
				</div>
			</td>
		</tr>

{% endfor %}
	
</table>









{% endblock %}




{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/homepage/templates/homepage/homepage2.html
{% extends "homepage/base.html" %} 
{% load staticfiles %}

{% block tabtitle %}  Query Tool {% endblock%}

{% block head %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script> -->
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="{% static 'research/jquery_chained/jquery.chained.js' %}" type="text/javascript" charset="utf-8"></script>


  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet"  href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  <link rel="stylesheet" href="{% static 'research/tablesorter/themes/blue/style.css' %}" type="text/css" media="print, projection, screen" />
  <script type="text/javascript" src="{% static 'research/tablesorter/jquery.tablesorter.js' %}"></script> 

<!-- <script type="text/javascript">
			$(function() {
			$("img.lazy").lazyload({failure_limit : 10});
		});
</script> -->

<script type="text/javascript">
function formsubmitreturn(formid,geturl,returndivid){
  $(formid).submit(function() { // catch the form's submit event
    $.ajax({ // create an AJAX call...
        data: $(this).serialize(), // get the form data
        type: $(this).attr('GET'), // GET or POST
        url: $(this).attr(geturl), // the file to call
        success: function(response) { // on success..
            $(returndivid).html(response); // update the DIV
        }
    });
    return false; // cancel original event to prevent form submitting
}
});
}
</script>

{% endblock %}

{% block title %}Home Page{% endblock %}

{% block pagetitle %} Home page {% endblock %}

{% block pagemain %} 

<script type="text/javascript">
{% for SQview in SQVIEW  %}	
	$(function() {
    		$("img.lazy").lazyload({ event: "scrollstop",failure_limit : 1000,container: $("#container{{forloop.counter0}}")});
  		});

{% endfor %}
</script>

<h1>DashBoard</h1>

<div style="margin: 0 auto;width: 90%;">	
<form id="savedqueriesform" onsubmit="" onload="" name="queryform_{{SQview.pk}}" action="{% url 'homepage:home' %}" method="get" style="text-align: center;margin: 0 auto;">

{% for SQview in SQVIEW  %}
	

	<table>
		<tr>
			<td>
				<h2 style="font-family: 'Ultra', sans-serif; font-weight: normal;margin: 1em 0 0.5em 0;">{{SQview.name}} </h2>
				<h3> date: {{SQview.date}}</h3>
				<div id="container{{forloop.counter0}}" style="border-radius: 25px; box-shadow: 10px 10px 5px #888888;background: #d6e0f5;padding: 20px;margin: 0 auto; white-space: nowrap;">
					
						<table>
							<tr><td>
								<table>
									<tr>
										{% for chrtname,chart in SQview.SummaryCharts.items %}
											{% if 'Industry' not in chrtname %}
											<td style="border-left: 1px solid #cdd0d4;">
												<h6>{{chrtname}}</h6>
												{{chart}}
											</td>
											{% endif %}
										{% endfor %}
									</tr>
								</table>
							</td></tr>
							<tr><td>
								<table>
									<tr>
								{% for chrtname,chart in SQview.SummaryCharts.items %}
									{% if 'Industry' in chrtname %}
									<td valign="top" style="border-left: 1px solid ">
										<h6>{{chrtname}}</h6>
										{{chart}}
									</td>
									{% endif %}
								{% endfor %}
									</tr>
								</table>
							</td></tr>
						</table>
						<table>
								<div id="tableofcharts_{{SQview.pk}}">
								{% for rows in SQview.Table  %}
									<tr>
									{% for img in rows  %}
										<td valign="top">{{img}}</td>
									{%endfor%}
									</tr>

								{% endfor %}
								</div>
						</table>
						<p>
						    <div class="pagination">
							    <span class="step-links">
							        {% if SQview.pages.has_previous %}
							        <input class="btn" value="previous" style="width:100px;" onclick="prevpage('pageno_{{forloop.counter0}}','#savedqueriesform',{{SQview.pages.previous_page_number}})" /> 
							            
							        {% endif %}

							        <span class="current">
							            Page {{ SQview.pages.number }} of {{ SQview.pages.paginator.num_pages }}.
							        </span>

							        {% if SQview.pages.has_next %}
									<input class="btn" value="next" style="width:100px;" onclick="nextpage('pageno_{{forloop.counter0}}','#savedqueriesform',{{SQview.pages.next_page_number}})" /> 

							        {% endif %}
							    </span>
							</div> 
						</p> 
						<input type="text" name="SQpk_{{forloop.counter0}}" value="{{SQview.pk}}">
						<input type="text" name="SQname_{{forloop.counter0}}" value="{{SQview.name}}">
						<input id="pageno_{{forloop.counter0}}" name="pageno_{{forloop.counter0}}" type="number" value="{{SQview.pageno}}"/>
				</div>
			</td>
		</tr>
	</table>

	






{% endfor %}
	
</form>
</div>	



<script type="text/javascript">
  function prevpage(pagenoid,formid,nextpageno){
 	document.getElementById(pagenoid).value=nextpageno;
 	$(formid).submit();
  }

  function nextpage(pagenoid,formid,nextpageno){
 	document.getElementById(pagenoid).value=nextpageno;
  	$(formid).submit();
  }
</script>


  <form id="ABCDEFGHAA_form" action="" method="post">
    <div id="ABCDEFGHAA_disp"></div>
    <p align="center"> <input type="hidden" onclick="formsubmitreturn('ABCDEFGHAA_form','okurl','ABCDEFGHAA_disp')" class="btn" name="tag_submit" value="Submit Category" /> </p>
  </form>


{% endblock %}




{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/homepage/templates/homepage/login.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  Register {% endblock%}

{% block title %}Register{% endblock %}



{% block pagetitle %} Register page {% endblock %}

{% block pagemain %} 

        <h1>Login</h1>
        Please <a href="{% url 'homepage:register' %}">register</a> if new user
        
        <!-- <form id="login_form" method="post" action="/stockdata/login/"> -->
      {% if next %}
      <form id="login_form" action="/login/?next={{next}}" method="post" >
      {%else%}
      <form id="login_form" action="/login/" method="post" >
      {% endif %}

            {% csrf_token %}

            <table  class="table table-striped">
            {{ user_form.as_table  }}
            </table>
           <!--  Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br /> -->

            <input type="submit" value="submit" />
        </form>

{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/homepage/templates/homepage/welcome.html
{% extends "homepage/base.html" %} 
{% load staticfiles %}

{% block tabtitle %}  Query Tool {% endblock%}

{% block head %}

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script> -->
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="{% static 'research/jquery_chained/jquery.chained.js' %}" type="text/javascript" charset="utf-8"></script>


  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet"  href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  <link rel="stylesheet" href="{% static 'research/tablesorter/themes/blue/style.css' %}" type="text/css" media="print, projection, screen" />
  <script type="text/javascript" src="{% static 'research/tablesorter/jquery.tablesorter.js' %}"></script> 

<!-- <script type="text/javascript">
			$(function() {
			$("img.lazy").lazyload({failure_limit : 10});
		});
</script> -->

<script type="text/javascript">
function formsubmitreturn(formid,geturl,returndivid){
  $(formid).submit(function() { // catch the form's submit event
    $.ajax({ // create an AJAX call...
        data: $(this).serialize(), // get the form data
        type: $(this).attr('GET'), // GET or POST
        url: $(this).attr(geturl), // the file to call
        success: function(response) { // on success..
            $(returndivid).html(response); // update the DIV
        }
    });
    return false; // cancel original event to prevent form submitting
}
});
}
</script>

{% endblock %}

{% block title %}Home Page{% endblock %}

{% block pagetitle %} Home page {% endblock %}

{% block pagemain %} 


<h1>Getting Started</h1>
<div style="font-size: 150%;border-radius: 25px;background:#ccffcc;padding: 20px;margin-left:10%;margin-right:10%;width: 80%;">
<ul>
	<li style="margin: 10px 0;"> Note: This website is still under development, but it still works and shows a proof of concept described below  </li>
	<li>See <a href="https://github.com/nadurthi/CompTechAnalysis">Github page</a> for the development code</li>

	<li style="margin: 10px 0;"> Please <a href="{% url 'homepage:register' %}">register</a> and <a href="{% url 'homepage:login' %}">login</a> </li>
	<li style="margin: 10px 0;"> The objective of this site is to search for interesting stocks. You can create a custom stock filter.</li>
	<li style="margin: 10px 0;"> For example check out the data set at <a href="{% url 'research:learning' %}">Data Set 1 </a>: Sort by target column for this table. All the rows labeled as Buy are stock that resulted in a minimum of 10% profit over 6 months. Rows with target variable as Sell are charts that resulted in a 10% loss. The goal is to develop a computational approach to recognize these trades.</li>

	<li style="margin: 10px 0;"> Filter the stocks that resulted in a profit, Most of the charts show some kind of pattern. Identify these patterns/features</li>
	<li style="margin: 10px 0;"> Are there any recurring patterns in the charts for the buy trades? If you find any recurring pattern, try representing it using stock price data and </li>
	<li style="margin: 10px 0;"> You can then <a href="{% url 'research:createmodifyfeature' %}">code up the features</a>. Or just the built-in ones available </li>
	<li style="margin: 10px 0;"> Once coded up, all the features are computed for all stocks everyday at midnight</li>
	<li style="margin: 10px 0;"> You can <a href="{% url 'research:windowquerytool_advanced' %}">create a filter/query</a> using any feature or all of them</li>
	<li style="margin: 10px 0;"> Save your filters/query and your filter will automatically run everyday, the results of which are shown on your homepage </li>
	<li style="margin: 10px 0;"> You can label/categorize each chart, which are then used in a classification algorithm </li>
</ul>


</div>
<h2 style="margin : 30px 30px;"> Identifying Patterns </h2>
<div style="font-size: 170%;border-radius: 25px;background:#ccffcc;padding: 20px;margin-left:10%;margin-right:10%;width: 80%;">

  For example, we want search for these patterns well before they start, as they sure do results in good returns. 
  	<table>
  		<tr>
  		<td> <img src="{% static 'homepage/TSLA_Desired_entry_point.png' %}" width="1000px" height="600px" >   </td>
		</tr>
  		<tr>
  		<td> <img src="{% static 'homepage/BDL_Desired_entry_point.png' %}"  width="1000px" height="600px" >   </td>
		</tr>
		<tr>
  		<td> <img src="{% static 'homepage/DNO_Desired_entry_point.png' %}"  width="1000px" height="600px" >   </td>
		</tr>
		<tr>
  		<td> <img src="{% static 'homepage/OVAS_Desired_entry_point.png' %}"  width="1000px" height="600px" >   </td>
		</tr>
		<tr>
  		<td> <img src="{% static 'homepage/SCO_Desired_entry_point.png' %}"  width="1000px" height="600px" >   </td>
		</tr>
	</table>

</div>






{% endblock %}




{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}