old_trademaster/stockdata/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views

app_name = 'stockdata'
urlpatterns = [

    url(r'^watchlistmanager/view/$', views.ViewStocksWatchLists, name='viewwatchlist'),

    url(r'^watchlistmanager/create/$', views.WatchListManager_create, name='watchlistmanager_create'),

    url(r'^watchlistmanager/amend/$', views.WatchListManager_amend, name='watchlistmanager_amend'),




    url(r'^controlpanel/$', views.ControlPanel, name='controlpanel'),
    
]

old_trademaster/stockdata/templates/stockdata/addstockmodel.html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

old_trademaster/stockdata/templates/stockdata/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{% block tabtitle %}  tab title {% endblock%}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">



	   <!-- <link rel="stylesheet" href="styles2.css"> -->
	   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	   <script src="script.js"></script>


		<!-- icons -->
		<!--link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png"-->
		<!--link rel="shortcut icon" href="favicon.ico"-->

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" type="text/css" href="{% static 'stockdata/styles_eg.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'stockdata/styles2.css' %}" />

	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">  {% block title%}Default title{% endblock%}  </h1>
			</div>
		</div>
		
		<!-- <div class="nav-bar">
			<div class="container">
				<ul class="nav">
				{% block navbar %} Nav bar items list {% endblock %} 
					
				</ul>
			</div>
		</div> -->

<div id='cssmenu'>


</div>


		<div class="content">
			<div class="container">
				<div class="main">
					{% block pagemain %} 

					Page 1 

					{% endblock %}
					
					

				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				{% block footer %} footer {% endblock %}
			</div>
		</div>
	</body>
</html>

old_trademaster/stockdata/templates/stockdata/controlpanel.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  Control Panel {% endblock%}

{% block title %}Control Panel{% endblock %}



{% block pagetitle %} Controller page {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}.</p>
{% else %}
    <!-- <p>Welcome, new user. Please <a href="{% url 'homepage:login' %}">log in</a></p> -->
    <a href="{% url 'homepage:login' %}?next={{request.path}}">Login to personalize</a>
{% endif %}


<p>
<font color="red">{{error|default_if_none:""}}</font>
</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><font color="red" size="4">{{ message }}</font></li>
    {% endfor %}
</ul>

{% endif %}




<h2>Celery Log</h2>
{{celerylog}}
<br>
<hr>
<br>

<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Run Seq 1 </h2>
    <table class="table table-striped">
      <tr><td><input type="submit" class="btn" name="Run_Seq_1" value="Run_Seq_1" /> </td></tr>
    </table>
</form>


<br>
<hr>
<br>


<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Run seq 2 </h2>
    <table class="table table-striped">
      <tr><td><input type="submit" class="btn" name="Run_Seq_2" value="Run_Seq_2" /> </td></tr>
    </table>
</form>


<br>
<hr>
<br>

<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Run seq 3 </h2>
    <table class="table table-striped">
      <tr><td><input type="submit" class="btn" name="Run_Seq_3" value="Run_Seq_3" /> </td></tr>
    </table>
</form>


<br>
<hr>
<br>


<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Load Stock Groups </h2>
    <table class="table table-striped">
      <tr><td><input type="submit" class="btn" name="load_stock_groups" value="Load StockGroups" /> </td></tr>
    </table>
</form>

<br>
<hr>
<br>

<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Update Watchlists </h2>
    <table class="table table-striped">
      <tr><td><input type="submit" class="btn" name="watch_update_stock" value="Update Watchlists" /> </td></tr>
    </table>
</form>


<br>
<hr>
<br>

<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Basic Initialization </h2>
    <table class="table table-striped">
        <tr><td><input type="submit" class="btn" name="basic_initialize" value="Basic Initialization" /> </td></tr>
    </table>
</form>


<br>
<hr>
<br>


<form action="{% url 'stockdata:controlpanel' %}" method="post">
    {% csrf_token %}
    <h2> Update Stock Data </h2>
    <table class="table table-striped">
    {{updatestockform.as_table}}  
    </table>
    <input type="submit" class="btn" name="update_stock_data" value="Update Stock Data" />
</form>


{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/stockdata/templates/stockdata/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'stockdata/style.css' %}" />

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

old_trademaster/stockdata/templates/stockdata/homepage.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  Home Page {% endblock%}

{% block title %}Home Page{% endblock %}

<blockquote>
    <p>The real names of our people were destroyed during slavery. </p>
    <footer><a href="http://en.wikipedia.org/wiki/Malcolm_X">Malcolm X</a></footer>
</blockquote>


{% block pagetitle %} Home page {% endblock %}

{% block pagemain %} 

<!-- {% if watchform.is_authenticated %}
    <p>Welcome, {{ watchform.get_username }}. Thanks for logging in.</p>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %} -->




{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/stockdata/templates/stockdata/results.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'stockdata/style.css' %}" />

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'detail' question.id %}">Vote again?</a>

old_trademaster/stockdata/templates/stockdata/watchlistmanager_amend.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  Watch List Modify  {% endblock%}

{% block title %}Watch List Modify {% endblock %}


{% block pagetitle %} Watch List Modify {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}.</p>
{% else %}
    <p>Welcome, new user. Please <a href="{% url 'homepage:login' %}">log in</a></p>
{% endif %}

<p>
<font color="red">{{error|default_if_none:""}}</font>
</p>


<h2> Modify Watch List </h2>
  <form action="{% url 'stockdata:watchlistmanager_amend' %}" method="post">
      {% csrf_token %}
      {{ watchform.errors }}
      
      <p>

      {% comment "Optional note" %}
      
        <table class="table table-striped">
        {{ watchform.as_table  }}
        </table>
      
      {% endcomment %}

      {{ watchform.watchlist.errors}}
      <table class="table table-striped">
      <tr>
        <td>{{watchform.watchlist.label_tag}}</td>  <td> {{watchform.watchlist}} </td>
      </tr>
      {% if watchform.symbols_append %}
      <tr>
        <td>{{watchform.symbols_append.label_tag}}</td>  <td> {{watchform.symbols_append}} </td>
      </tr>
      {%  endif %}
      </table>

      {% if watchform.symbols_length_del  %}
        <table >
        <tr><th> Delete </th> <th> Symbol </th></tr>
        {% for field in watchform %}
          {% if field.label != watchform.watchlist.label and field.label != watchform.symbols_append.label  %}
            <tr> <td> {{field}} </td> <td> {{ field.label }} </td> </tr>
          {% endif %}  
        {% endfor %}
        </table>
      {% endif %}

      </p>
      {% if watchform.symbols_length_del  %}
        <p align="center"> <input type="submit" class="btn" name="watch_save" value="Save Changes" /> </p>
      {% else %}
       <p align="center"> <input type="submit" class="btn" name="watch_submit" value="Select Watchlist" /> </p>
      {% endif %}
  </form>


<br>


{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/stockdata/templates/stockdata/watchlistmanager_create.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  Watch List Create  {% endblock%}

{% block title %}Watch List Create {% endblock %}


{% block pagetitle %} Watch List Create {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }} .</p>
{% else %}
    <p>Welcome, new user. Please <a href="{% url 'homepage:login' %}">log in</a></p>
{% endif %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><font color="red" size="4">{{ message }}</font></li>
    {% endfor %}
</ul>

{% endif %}

<h2> Create New Watch List </h2>
  <form action="{% url 'stockdata:watchlistmanager_create' %}" method="post">
      {% csrf_token %}
      {{ createwatchlistform.errors }}
      <table class="table table-striped">
        {{ createwatchlistform.as_table  }}
      </table>
      <p align="center"> <input type="submit" class="btn" name="watch_create" value="Create Watchlist" /> </p>
  </form>




<br>


{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/stockdata/templates/stockdata/watchlistmanager_view.html
{% extends "homepage/base.html" %} 

{% block tabtitle %}  View List Modify  {% endblock%}

{% block title %}Watch List Modify {% endblock %}


{% block pagetitle %} Watch List View {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}.</p>
{% else %}
    <p>Welcome, new user. Please <a href="{% url 'homepage:login' %}">log in</a></p>
{% endif %}

<p>
<font color="red">{{error|default_if_none:""}}</font>
</p>


<h2> View Watch List </h2>
  <form action="{% url 'stockdata:viewwatchlist' %}" method="post">
      {% csrf_token %}
      {{ watchformview.errors }}
      
      <p>

      {% comment "Optional note" %}
      
        <table class="table table-striped">
        {{ watchformview.as_table  }}
        </table>
      
      {% endcomment %}

      {{ watchformview.watchlist.errors}}
      <table class="table table-striped">
      <tr>
        <td>{{watchformview.watchlist.label_tag}}</td>  <td> {{watchformview.watchlist}} </td>
      </tr>
      </table>

      <table >
      {% for ss in watchformview.symbs  %}
        <tr><td> {{ss}} </th></tr>     
      {% endfor %}
      </table>
      </p>
       <p align="center"> <input type="submit" class="btn" name="watch_view" value="View Watchlist" /> </p>
  </form>


<br>


{% endblock %}

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}