old_trademaster/research/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views

app_name = 'research'
urlpatterns = [
    
    url(r'^querytool/$', views.QueryTool, name='querytool'),
    url(r'^windowquerytool_advanced/$', views.WindowQueryTool_advanced, name='windowquerytool_advanced'),

    url(r'^createmodifyfeature/$', views.CreateModifyFeature, name='createmodifyfeature'),

    url(r'^categories/$', views.CategoryManager, name='category'),
    url(r'^tagsubmit/$', views.tagsubmit, name='tagsubmit'),
    url(r'^study/$', views.Study, name='study'),
    url(r'^status/$', views.ResearchStatus, name='researchstatus'),

    url(r'^logs/$', views.ComputeLog, name='ComputeLog'),

    url(r'^learning/$', views.Learning, name='learning'),
    
    
    
]

old_trademaster/research/forms.py
from __future__ import division
from django.db.models import Q
from django.conf import settings
import stockdata.models as stkmd
import charting.models as chrtmd
from . import models as md
import logging
logger = logging.getLogger(__name__)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import pandas as pd
import numpy as np
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
import collections
from django.forms import ModelForm
from django import forms
from django.core.validators import RegexValidator
import research.featuremanager as featmng
import json
import time

import pdb



## model helpers-----------------------------------------------------------------------------

def LoadUpSavedQueries_choices(user):
	Coljson={'None'.encode('utf-8'):''.encode('utf-8')}
	Filjson={'None'.encode('utf-8'):''.encode('utf-8')}
	SavedQmeta_options={'None'.encode('utf-8'):''.encode('utf-8')}

	SQ=md.SavedQueries.objects.filter(user=user)
	choices=[('None','-----')]
	for ss in SQ:
		choices.append( (str(ss.pk), ss.Queryname) )
		Coljson[str(ss.pk).encode('utf-8')]=ss.Coljson.encode('utf-8')
		Filjson[str(ss.pk).encode('utf-8')]=ss.Filjson.encode('utf-8')
		SavedQmeta_options[str(ss.pk).encode('utf-8')]={}
		if ss.Queryname==None:
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['name']=''
		else:
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['name']=ss.Queryname.encode('utf-8')
		if ss.Querydescription==None:
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['desc']=''
		else:
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['desc']=ss.Querydescription.encode('utf-8')


	if str(user)!='@general@':
		SQ=md.SavedQueries.objects.filter(user__username='@general@')
		for ss in SQ:
			if ss.Queryname=='StockMarket':
				continue
				
			choices.append( (str(ss.pk), ss.Queryname) )
			Coljson[str(ss.pk).encode('utf-8')]=ss.Coljson.encode('utf-8')
			Filjson[str(ss.pk).encode('utf-8')]=ss.Filjson.encode('utf-8')
			SavedQmeta_options[str(ss.pk).encode('utf-8')]={}
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['name']=ss.Queryname.encode('utf-8')
			SavedQmeta_options[str(ss.pk).encode('utf-8')]['desc']=ss.Querydescription.encode('utf-8')	

	return choices,Coljson,Filjson,SavedQmeta_options


def LoadUpGeneralFeature_choices(user):
	GF=md.GeneralFeature.objects.filter(user=User.objects.get(username='@general@'))
	choices=[(str(ss.pk), ss.name) for ss in GF]
	choices=choices+[('None','-----')]

	if str(user)!='@general@':
		GF=md.GeneralFeature.objects.filter(user=user)
		choices=choices+[(str(ss.pk), ss.name) for ss in GF]
	
	return choices



def StockAlphabetGrpCont_forchartname(symbs):
	if symbs==None:
		return 'AllStocks'
	symbs=sorted(symbs)
	symbs=[ss[0] for ss in symbs]

	# Alpha=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
	# pdb.set_trace()
	counter=collections.Counter(symbs)
	ss=''
	for key,value in dict(counter).items():
		ss=ss+str(key)+str(value)
	return ss







## -------------------------------FORMS  --------------------------------


class CreateModifyFeatureForm(forms.Form):
	alphanumeric = RegexValidator(r'^[a-zA-Z][_0-9a-zA-Z]*$', 'Should Begin with alphabet and the name should contain only alphanumeric characters or "_" .')
	customfeature_code = forms.CharField(label='enter feature code here',widget=forms.Textarea,required=False)
	customfeature_name = forms.CharField(label='feature name',required=False, validators=[alphanumeric])
	customfeature_description = forms.CharField(label='feature description',widget=forms.Textarea(attrs={'rows': 2,'cols': 50,}),required=False)
	customfeature_group = forms.CharField(label='Enter a feature group',widget=forms.TextInput,required=False)
	
	select_group=forms.ChoiceField(label='Select the Group', widget=forms.Select,choices=[],initial='None') #choices=intervals

	operators=forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=[(ss.operators,md.FeatureOperator.choices[ss.operators]) for ss in md.FeatureOperator.objects.all()],
		initial=[ss.operators for ss in md.FeatureOperator.objects.all()],
	)
	units=forms.MultipleChoiceField(
		required=False,
		widget=forms.CheckboxSelectMultiple,
		choices=[(ss.units,md.FeatureUnit.choices[ss.units]) for ss in md.FeatureUnit.objects.all()],
		initial=[ss.units for ss in md.FeatureUnit.objects.all()],
	)

	def __init__(self, *args, **kwargs):
		self.user=kwargs.pop('user')
		self.username=str(self.user)
		super(CreateModifyFeatureForm, self).__init__(*args, **kwargs)
		self.user,self.username=stkmd.CleanUpUser(self.user)

		self.fields['select_group'].choices=[('None','Select')]+[(ss,ss) for ss in list(set(md.GeneralFeature.objects.values_list('group',flat=True))) ]
		self.nameisset=None

		with featmng.featuremanager() as FM:
			FM.LoadTestData()
			FM.LoadFeatureModule()
			testmeta=FM.testmeta

		# testdata,t0,T,window,Interval,Symbol=GetFeatureTestData()

			genfeats=md.GeneralFeature.objects.filter(user__username='@general@').exclude(name__in=['FutMNRtQt','FutMNRtHf','FutMNRtAn','PastMNRtQt','PastMNRtHf','PastMNRtAn','FutMXRtQt','FutMXRtHf','FutMXRtAn','PastMXRtQt','PastMXRtHf','PastMXRtAn']).order_by('group')
			if str(self.user)!='@general@':
				userfeats=md.GeneralFeature.objects.filter(user=self.user).order_by('group')


			self.SavedGenfeatures=[]
			for gg in genfeats:
				# testdata['code_str']=gg.code
				# testdata['name']=gg.name
				a=FM.TestFeatures(gg.name)
				# a=featex.check_feature_code(testdata.copy(),gg.code,gg.name)
				self.SavedGenfeatures.append( {'output':a,'type':'general','group':gg.group,'id':gg.pk, 'description': gg.description,'code':gg.code,'name':gg.name  }   )


			self.SavedUserfeatures=[]
			for gg in userfeats:
				# testdata['code_str']=gg.code
				# testdata['name']=gg.name
				# a=featex.check_feature_code(testdata.copy(),gg.code,gg.name)
				a=FM.TestFeatures(gg.name)
				self.SavedUserfeatures.append( {'output':a,'type':'user','group':gg.group,'id':gg.pk, 'description': gg.description,'code':gg.code,'name':gg.name}   )

		self.featvalue=None
		
		if chrtmd.UploadCharts.objects.filter(chartname='FeatureCreateTestPlot',chartsrc='C',chartstyle=chrtmd.StdChartProps.objects.get(chartstylename='@defaultlinear@',user__username='@general@'), 
								window=testmeta['window'],Interval=testmeta['Interval'],T=testmeta['T'],Symbol=stkmd.Stock.objects.get(Symbol=testmeta['Symbol']),
								user=User.objects.get(username='@general@')).exists():
			upch=chrtmd.UploadCharts.objects.get(chartname='FeatureCreateTestPlot',chartsrc='C',chartstyle=chrtmd.StdChartProps.objects.get(chartstylename='@defaultlinear@',user__username='@general@'), 
								window=testmeta['window'],Interval=testmeta['Interval'],T=testmeta['T'],Symbol=stkmd.Stock.objects.get(Symbol=testmeta['Symbol']),
								user=User.objects.get(username='@general@'))
		else:
			upch=chrtmd.UploadCharts(chartname='FeatureCreateTestPlot',chartsrc='C',chartstyle=chrtmd.StdChartProps.objects.get(chartstylename='@defaultlinear@',user__username='@general@'), 
								window=testmeta['window'],Interval=testmeta['Interval'],T=testmeta['T'],Symbol=stkmd.Stock.objects.get(Symbol=testmeta['Symbol']),
								user=User.objects.get(username='@general@'))
			upch.save()

		self.chart=upch.GetorMakeChartUrls()

	def GenerateInitialdefCode(self):
		self.nameisset=True
		name=self.cleaned_data['customfeature_name']
		# self.cleaned_data['customfeature_code']='def '+name+'(data):\r\n\t#numpy available as np\r\n\t#pandas available as pd\r\n\t# No other module can be used\r\n\tT=data["T"]\r\n\tdf=data["df"]\r\n\tTrendsMid=data["TrendsMid"]\r\n\tTrendsTop=data["TrendsTop"]\r\n\tTrendsBottom=data["TrendsBottom"]\r\n\t# Use data["DebugOutput"] to show output for debugging\r\n\t'
		
		with featmng.featuremanager() as FM:
			self.cleaned_data['customfeature_code']=FM.GetEmptyFeatCode_str(name)

		self.cleaned_data['operators']=[ss.operators for ss in md.FeatureOperator.objects.all() if ss.operators!='contains']
		self.cleaned_data['units']=[ss.units for ss in md.FeatureUnit.objects.all() if ss.units!='%']
		

	def SaveFeatureCode(self):
		if md.GeneralFeature.objects.filter(user__username='@general@',name=self.cleaned_data['customfeature_name']).exists():
			return (False,'Feature name already exists in general(public) category, use the general feature or rename your feature',None)
		if self.user.username!='@general@':
			if md.GeneralFeature.objects.filter(user=self.user,name=self.cleaned_data['customfeature_name']).exists():
				return (False,'Feature name already exists, use a different name or modify the esisting feature',None)

		# get a test data to check if the feature works well
		# testdata,t0,T,window,Interval,Symbol=GetFeatureTestData()
		# testdata['code_str']=self.cleaned_data['customfeature_code']
		# testdata['name']=self.cleaned_data['customfeature_name']
		with featmng.featuremanager() as FM:
			FM.LoadTestData()
			a=FM.CheckFeaturecode_str(self.cleaned_data['customfeature_name'],self.cleaned_data['customfeature_code'])
			# a=featex.check_feature_code(testdata,self.cleaned_data['customfeature_code'],self.cleaned_data['customfeature_name'])
		
		if a[0]==True:
			if md.GeneralFeature.objects.filter(user=self.user,name=self.cleaned_data['customfeature_name']).exists():
				GF=md.GeneralFeature.objects.get(user=self.user,name=self.cleaned_data['customfeature_name'])
				GF.code=self.cleaned_data['customfeature_code']
				GF.group=self.cleaned_data['customfeature_group']
				GF.description=self.cleaned_data['customfeature_description']
				operators=list(GF.operators.all())
				
				for op in operators:
					GF.operators.remove(op)
				units=list(GF.units.all())
				for un in units:
					GF.units.remove(un)
				# pdb.set_trace()
				GF.operators.add(*md.FeatureOperator.objects.filter(operators__in=self.cleaned_data['operators']))

old_trademaster/research/templates/research/Learning.html
{% extends "homepage/base.html" %} 
{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block tabtitle %}  Query Tool {% endblock%}

{% block head %}

      <script src="{% static 'research/RedQueryBuilder/RedQueryBuilder.nocache.js' %}" type="text/javascript">//</script>
      <link rel="stylesheet" href="{% static 'research/RedQueryBuilder/gwt/dark/dark.css' %}" type="text/css" />
      <script src="{% static 'research/RedQueryBuilder/RedQueryBuilderFactory.nocache.js' %}" type="text/javascript">//</script>
     
      <meta charset="utf-8">
  <title>jQuery UI Sortable - Connect lists</title>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <!--script src="http://code.jquery.com/jquery-1.10.2.js"></script -->
  <!-- script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script -->

   <script type="text/javascript" src="{% static 'research/jquery_tablesorter/jquery.tablesorter.js' %}"></script> 
  <script type="text/javascript" src="{% static 'research/jquery_tablesorter/themes/blue/style.css' %}"></script> 

  <link rel="stylesheet"  href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  
  <link rel="stylesheet" href="{% static 'research/tablesorter/themes/blue/style.css' %}" type="text/css" media="print, projection, screen" />
  <!-- script type="text/javascript" src="{% static 'research/tablesorter/jquery-latest.js' %}"></script --> 
  <script type="text/javascript" src="{% static 'research/tablesorter/jquery.tablesorter.js' %}"></script> 


<script type="text/javascript">
  $(document).ready(function() 
    { 
        $("#myTable").tablesorter(); 
    } 
); 
   
</script>

<style type="text/css">
  th.rotate {
  /* Something you can count on */
  height: 140px;
  white-space: nowrap;
}

th.rotate > div {
  transform: 
    /* Magic Numbers */
    /*translate(25px, 51px)*/
    /* 45 is really 360 - 45 */
    rotate(270deg);
  width: 15px;
}
th.rotate > div > span {
  /*border-bottom: 1px solid #ccc;*/
  padding: 5px 10px;
}

</style>
{% endblock %}


{% block title %}Query Tool{% endblock %}







{% block pagetitle %} Query Tool {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}.</p>
{% else %}
    <a href="{% url 'homepage:login' %}?next={{request.path}}">Login to personalize</a>
{% endif %}



<form id="formid" action="{% url 'research:learning' %}" method="get">

<p>
{{Learning.description}}
</p>

{% if Learning.pageno %}
<input id="pageno" name="pageno" type="number" value="{{Learning.pageno}}" /> 
{% else %}
<input id="pageno" name="pageno" type="number" /> 
{% endif %}

<input class="btn" value="previous" style="width:100px;" onclick="prevpage('pageno','#formid',{{Learning.pageno}})" /> 
<input class="btn" value="next" style="width:100px;" onclick="nextpage('pageno','#formid',{{Learning.pageno}})" />  


{{ Learning.table }}

</form>




<script type="text/javascript">
  function prevpage(pagenoid,formid,prevpageno){
  document.getElementById(pagenoid).value=prevpageno-1;  
  $(formid).submit();
  }

  function nextpage(pagenoid,formid,nextpageno){
  document.getElementById(pagenoid).value=nextpageno+1;
    $(formid).submit();
  }
</script>



{% endblock %} 

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}

old_trademaster/research/templates/research/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{% block tabtitle %}  tab title {% endblock%}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="ADD AUTHOR INFORMATION">
		<meta name="robots" content="index, follow">



	   <!-- <link rel="stylesheet" href="styles2.css"> -->
	   <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	   <script src="script.js"></script>


		<!-- icons -->
		<!--link rel="apple-touch-icon" href="assets/img/apple-touch-icon.png"-->
		<!--link rel="shortcut icon" href="favicon.ico"-->

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" type="text/css" href="{% static 'research/styles_eg.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'research/styles2.css' %}" />

		{% block head %}

		{% endblock %} 


	</head>
	<body>
		<div class="header">
			<div class="container">
				<h1 class="header-heading">  {% block title%}Default title{% endblock%}  </h1>
			</div>
		</div>


<div id='cssmenu'>

{% block navbar2 %}

{% endblock %} 
</div>


		<div class="content">
			<div class="container">
				<div class="main">
					{% block pagemain %} 

					Page 1 

					{% endblock %}
					
					

				</div>
			</div>
		</div>
		<div class="footer">
			<div class="container">
				{% block footer %} footer {% endblock %}
			</div>
		</div>
	</body>
</html>

old_trademaster/research/templates/research/createmodifyfeature.html
{% extends "homepage/base.html" %} 
{% load staticfiles %}
{% load render_table from django_tables2 %}

{% block tabtitle %}  Query Tool {% endblock%}

{% block head %}


     
      <meta charset="utf-8">

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <!-- <script src="http://code.jquery.com/jquery-1.10.2.js"></script> -->
  <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

  <!--script src="http://code.jquery.com/jquery-1.10.2.js"></script -->
  <!-- script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script -->

  <link rel="stylesheet"  href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
  
  <link rel="stylesheet" href="{% static 'research/tablesorter/themes/blue/style.css' %}" type="text/css" media="print, projection, screen" />
  <!-- script type="text/javascript" src="{% static 'research/tablesorter/jquery-latest.js' %}"></script --> 
  <script type="text/javascript" src="{% static 'research/tablesorter/jquery.tablesorter.js' %}"></script> 
  <script src="{% static 'research/ace/src-noconflict/ace.js' %}" type="text/javascript" charset="utf-8"></script>
 
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">s
  <style type="text/css" media="screen">

/*
    #editor_create {
        margin: 10;
        position: fixed;
        top: 5;
        bottom: 5;
        left: 5;
        right: 5;
    }*/
  </style>

  <style>
  .ui-autocomplete {
    max-height: 100px;
    overflow-y: auto;
    /* prevent horizontal scrollbar */
    overflow-x: hidden;
  }
  /* IE 6 doesn't support max-height
   * we use height instead, but this forces the menu to always be this tall
   */
  * html .ui-autocomplete {
    height: 100px;
  }
  </style>
  <style type="text/css">
    #id_operators li,#id_units li{
    list-style-type: none;
    /*margin: 1px;
    padding: 1px;*/
    background-color:#b3cccc;
    display:inline;
    border: 1px solid #eee;
    
    }
  </style>
{% endblock %}


{% block title %}Create Features{% endblock %}







{% block pagetitle %} Create Features {% endblock %}

{% block pagemain %} 

{% if user.is_authenticated %}
    <p>Welcome, {{ user.get_username }}.</p>
{% else %}
    <!-- <p>Welcome, new user. Please <a href="{% url 'homepage:login' %}">log in</a></p> -->
    <a href="{% url 'homepage:login' %}?next={{request.path}}">Log in to create and view custom categories</a>
{% endif %}


<p>
<font color="red">{{error|default_if_none:""}}</font>
</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><font color="red" size="4">{{ message }}</font></li>
    {% endfor %}
</ul>

{% endif %}


    

    <form action="{% url 'research:createmodifyfeature' %}" method="post">
    {% csrf_token %}
    
      <h2>Create a new Feature</h2>
      <table>
      <tr>
      <td>{{CreateModifyFeatureForm.customfeature_name.label}}</td> <td>{{CreateModifyFeatureForm.customfeature_name}}</td>
      </tr>
      <tr>
      <td>{{CreateModifyFeatureForm.customfeature_description.label}}</td> <td>{{CreateModifyFeatureForm.customfeature_description}}</td>
      </tr>
      <tr>
      <td>Select or enter a group</td> <td> <div class="ui-widget">{{CreateModifyFeatureForm.select_group}} {{CreateModifyFeatureForm.customfeature_group}} </div></td>
      </tr>
      
      {% if CreateModifyFeatureForm.nameisset %}
      <tr>
        <td>Select applicable operators for query </td><td>{{CreateModifyFeatureForm.operators}}</td>
      </tr>
      <tr>
        <td>Select applicable units for query</td><td >{{CreateModifyFeatureForm.units}}</td>
      </tr>
      <tr>
      <td>{{CreateModifyFeatureForm.customfeature_code.label}}</td> <td>{{CreateModifyFeatureForm.customfeature_code}}</td>
      </tr>

      {% endif %}
      </table>


      {% if CreateModifyFeatureForm.nameisset %}


<p align="center">
<pre id="editor_create" style="width:1000px;height:300px;overflow: auto;">

</pre>
</p>


      {% endif %}

    {% if CreateModifyFeatureForm.nameisset %}
    <p align="center"> <input type="submit" class="btn" name="feature_create_save" value="Save New Feature" /> </p>
    {% else %}
    <p align="center"> <input type="submit" class="btn" name="feature_create" value="Create Feature" /> </p>
    {% endif %}


    {% if CreateModifyFeatureForm.featvalue %}
    <h2> Computed Feature value = {{CreateModifyFeatureForm.featvalue}}</h2>
    {% endif %}

    {% if CreateModifyFeatureForm.chart %}
    {{CreateModifyFeatureForm.chart}}
    {% endif %}

<br>
<br>
<div style="position:static;">
<hr>
<br>


<h2>View/Modify Features</h2>


    
 {% for feat in CreateModifyFeatureForm.SavedGenfeatures %}
    <br>
    <br>
    <h3>Group: {{feat.group}}</h3>
    <p>Feature Name: {{feat.name}}</p>
    <p>Description: {{feat.description}}</p>
    <p>Output: {{feat.output}}</p>
    <textarea id="textcode_{{feat.id}}">{{feat.code}}</textarea>
    <p align="center">
    <pre id="editor_create_{{feat.id}}" style="width:1000px;height:300px;overflow: auto;">

    </pre>
    </p>

  {% endfor %}

  {% for feat in CreateModifyFeatureForm.SavedUserfeatures %}
    <br>
    <br>
    <h3>Group: {{feat.group}}</h3>
    <p>Feature Name: {{feat.name}}</p>
    <p>Description: {{feat.description}}</p>
    <p>Output: {{feat.output}}</p>
      <textarea name="textcode_{{feat.id}}" id="textcode_{{feat.id}}">{{feat.code}}</textarea>
    <p align="center">
      <pre id="editor_create_{{feat.id}}" style="width:1000px;height:300px;overflow: auto;">  </pre>
    </p>
    <table style="width:1000px">
    <tr>
      <td align="left"><input type="submit" class="btnreset" name="feature_modify_{{feat.id}}" value="Delete Feature" /></td>
      <td align="right"><input type="submit" class="btn" name="feature_modify_{{feat.id}}" value="Modify Feature" /></td>
    </tr> 
    </table>
    

  {% endfor %}

    </form>





</div>




<body onload="master_func_onload();">
<script type="text/javascript">
  function master_func_onload(){
 {% for feat in CreateModifyFeatureForm.SavedGenfeatures %}
  load_create_editor_viewmodify('textcode_{{feat.id}}','editor_create_{{feat.id}}');
{% endfor %}
  
  {% for feat in CreateModifyFeatureForm.SavedUserfeatures %}
  load_create_editor_viewmodify('textcode_{{feat.id}}','editor_create_{{feat.id}}');
  {% endfor %}

  load_create_editor();

}
</script>



<script>

function load_create_editor() {
  // alert(document.getElementById('feat').innerText);

    
    document.getElementById('editor_create').textContent=document.getElementById('id_customfeature_code').value;

    var editor = ace.edit("editor_create");
    editor.setTheme("ace/theme/twilight");
    editor.session.setMode("ace/mode/python");
    document.getElementById('editor_create').style.fontSize='15px';
    // editor.setReadOnly(true);  // false to make it editable
    editor.setHighlightActiveLine(false);
    editor.setShowPrintMargin(false);
    

    editor.on("change", function(){
      // alert(editor.getSession().getValue());
      document.getElementById('id_customfeature_code').value= editor.getSession().getValue();
      // alert(document.getElementById('id_customfeature_code').value);


    });

}

function load_create_editor_viewmodify(idformcode,ideditorcode) {
  // alert(document.getElementById('feat').innerText);

    
    document.getElementById(ideditorcode).textContent=document.getElementById(idformcode).value;

    var editor = ace.edit(ideditorcode);
    editor.setTheme("ace/theme/twilight");
    editor.session.setMode("ace/mode/python");
    document.getElementById(ideditorcode).style.fontSize='15px';
    // editor.setReadOnly(true);  // false to make it editable
    editor.setHighlightActiveLine(false);
    editor.setShowPrintMargin(false);
    

    editor.on("change", function(){
      // alert(editor.getSession().getValue());
      document.getElementById(idformcode).value= editor.getSession().getValue();
      // alert(document.getElementById('id_customfeature_code').value);


    });

}

$('#id_select_group').on('change',function(){
  var e=document.getElementById('id_select_group');
  var txt=e.options[e.selectedIndex].text;
  alert(txt);
  if (txt=='Select'){
   document.getElementById('id_customfeature_group').value='';     
  }
  else{
   document.getElementById('id_customfeature_group').value=e.options[e.selectedIndex].text;    
  }

   e.selectedIndex=0;

});

</script>



{% endblock %} 

{% block footer %} 

Copyright of Nagavenkat Adurthi

 {% endblock %}